base_url = "http://jonathan-kelley.com/ConceptMaps/topics/"
compile_sass = true
title = "Discrete Concept Map"
description = "Concepts, explanations, and knowledge for Discrete Mathematics"
theme = "hyde"
